### PR TITLE
CJS -> ES Migration

### PR DESCRIPTION
**Pull request by rfrabasile**

### CODE REVIEW

**Review by adrianbona — APPROVED** [review]
LGTM

**Comment by adrianbona** [comment]
@rfrabasile please make sure the conflict is resolved

**Comment by rfrabasile** [comment]
all conflicts resolved, atm

**Comment by ACatThatPrograms** [comment]
Have we tried importing this module into a standard server side nodejs application and making sure ES is supported there?

Currently nodejs doesn't support ES out of the box, so I am concerned if this was being used in a server context that it would cause problems for end users. Just want to avoid issues of a syntax migration.

**Comment by ACatThatPrograms** [comment]
Closing in lieu of the TypeScript update. We will rollup to both CJS and EJS

**Pull request closed without merging**
